id: 384d16d7c8554e3dacae94551694fe35
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_515-Dharani_of_Buddha's_Essence-v2.bo.en
  language: bo
  author: ''
  volume: {}
